live_config_reload = true

[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 0.85
decorations = "Transparent"

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "PlemolJP35 Console NF", style = "Regular" }
bold = { family = "PlemolJP35 Console NF", style = "Bold" }
italic = { family = "PlemolJP35 Console NF", style = "Italic" }
bold_italic = { family = "PlemolJP35 Console NF", style = "Bold Italic" }
size = 14.0
offset = { x = 0, y = 2 }
